import { CsShipmentSurcharge } from "./csShipmentSurcharge";
import { TransactionTypeEnum } from "../../enums/transaction-type.enum";

export class AcctCDNote {
  id: String = "00000000-0000-0000-0000-000000000000";
  code: String = null;
  jobId: String = null;
  branchId: String = "00000000-0000-0000-0000-000000000000";
  partnerId: String = null;
  partnerName: String = null;
  type: String = null;
  paymentDueDate: Date = null;
  customerPaid: boolean = null;
  paidDate: Date = null;
  sentToCustomer: boolean = null;
  sentByUser: String = null;
  sentOn: String = null;
  total: number = null;
  exportedDate: Date = null;
  unlockedDirector: String = null;
  unlockedDirectorStatus: String = null;
  unlockedDirectorDate: String = null;
  unlockedSaleMan: String = null;
  unlockedSaleManStatus: String = null;
  unlockedSaleManDate: String = null;
  invoiceNo: String = null;
  userCreated: String = null;
  datetimeCreated: Date = null;
  userModified: String = null;
  datetimeModified: Date = null;
  statementDate: Date = null;
  currencyId: String = null;
  customerConfirmDate: String = null;
  numberDayOverDue: number = null;
  alertNumberDayOverDueEmail: boolean = null;
  paidPrice: number = null;
  freightPrice: number = null;
  behalfPrice: number = null;
  paidFreightPrice: number = null;
  paidBehalfPrice: number = null;
  trackingTransportBill: String = null;
  trackingTransportDate: String = null;
  listShipmentSurcharge: CsShipmentSurcharge[] = [];
  transactionTypeEnum: TransactionTypeEnum = 0;
}