export class Container {
  id: string = null;
  containerType: string = null;
  containerQuantity: number = null;
  containerNo: string = null;
  sealNo: string = null;
  markNo: string = null;
  commodityId?: number = null;
  packageTypeId: string = null;
  goodsDescription: string = null;
  grossWeight: number = 0;
  netWeight: number = 0;
  chargeAbleWeight: number = 0;
  unitId: number = null;
  cbm: number = 0;
  userCreated: string = null;
  datetimeCreated: Date = null;
  userModified: string = null;
  datetimeModified: Date = null;
  inactive: boolean = null;
  inactiveOn: Date = null;
  jobId: string = null;
  hblno: string = null;
  isSave: boolean = false;
}