export class SeaFCLExport {
  jobId: string = null;
  estimatedTimeofDepature: Date = null;
  estimatedTimeofArrived: Date = null;
  mblno: string = null;
  masterBillOfLoadingType: string = null;
  coloaderId: string = null;
  bookingNo: string = null;
  serviceType: string = null;
  agentId: string = null;
  portOfLoading: string = null;
  portOfDestination: string = null;
  term: string = null;
  vesselName: string = null;
  voyNo: string = null;
  shippingType: string = null;
  purchaseOrderNo: string = null;
  personInChargeId: string = null;
  note: string = null;
  commoditiesDescription: string = null;
  goodsDescription: string = null;
  userCreated: string = null;
  datetimeCreated: Date = null;
  userModified: string = null;
  datetimeModified: Date = null;
  inactive: boolean = null;
  inactiveOn: Date = null;
}