for %%d in (
	..\eFMS.API.SystemWeb\eFMS.IdentityServer\eFMS.IdentityServer.DAL,
	..\eFMS.API.SystemWeb\eFMS.IdentityServer\eFMS.IdentityServer.DL,
	..\eFMS.API.SystemWeb\eFMS.IdentityServer\eFMS.IdentityServer,
	..\eFMS.API.SystemWeb\eFMS.API.Accounting\eFMS.API.Accounting.DAL,
	..\eFMS.API.SystemWeb\eFMS.API.Accounting\eFMS.API.Accounting.DL,
	..\eFMS.API.SystemWeb\eFMS.API.Accounting\eFMS.API.Accounting,
	..\eFMS.API.SystemWeb\eFMS.API.Catalogue\eFMS.API.Catalogue.DAL,
	..\eFMS.API.SystemWeb\eFMS.API.Catalogue\eFMS.API.Catalogue.DL,
	..\eFMS.API.SystemWeb\eFMS.API.Catalogue\eFMS.API.Catalogue,
	..\eFMS.API.SystemWeb\eFMS.API.Documentation\eFMS.API.Documentation.DAL,
	..\eFMS.API.SystemWeb\eFMS.API.Documentation\eFMS.API.Documentation.DL,
	..\eFMS.API.SystemWeb\eFMS.API.Documentation\eFMS.API.Documentation,
	..\eFMS.API.SystemWeb\eFMS.API.Operation\eFMS.API.Operation.DAL,
	..\eFMS.API.SystemWeb\eFMS.API.Operation\eFMS.API.Operation.DL,
	..\eFMS.API.SystemWeb\eFMS.API.Operation\eFMS.API.Operation,
	..\eFMS.API.SystemWeb\eFMS.API.Setting\eFMS.API.Setting.DAL,
	..\eFMS.API.SystemWeb\eFMS.API.Setting\eFMS.API.Setting.DL,
	..\eFMS.API.SystemWeb\eFMS.API.Setting\eFMS.API.Setting,
	..\eFMS.API.SystemWeb\eFMS.API.System\eFMS.API.System.DAL,
	..\eFMS.API.SystemWeb\eFMS.API.System\eFMS.API.System.DL,
	..\eFMS.API.SystemWeb\eFMS.API.System\eFMS.API.System,
	..\eFMS.API.SystemWeb\eFMS.API.ReportData
) do dotnet build "%%d"