using System;
using System.Collections.Generic;

namespace SystemManagementAPI.Service.Models
{
    public partial class CsOrderDetail
    {
        public Guid Id { get; set; }
        public string Code { get; set; }
        public byte[] CodeBarCode { get; set; }
        public Guid OrderId { get; set; }
        public string Awb { get; set; }
        public byte[] AwbbarCode { get; set; }
        public Guid? OriginBranchId { get; set; }
        public Guid? OriginHubId { get; set; }
        public Guid? DestinationBranchId { get; set; }
        public Guid? DestinationHubId { get; set; }
        public string QuotedRouteType { get; set; }
        public int? CurrentStatusId { get; set; }
        public string Receptacle { get; set; }
        public DateTime? PickupRequestDate { get; set; }
        public short? PickupRequestTime { get; set; }
        public DateTime? PickupConfirmDate { get; set; }
        public short? PickupConfirmTime { get; set; }
        public string PickupCompany { get; set; }
        public string PickupContactPerson { get; set; }
        public string PickupContactNo { get; set; }
        public string PickupMobileNo { get; set; }
        public string PickupAddress { get; set; }
        public Guid? PickupWardId { get; set; }
        public Guid? PickupDistrictId { get; set; }
        public Guid? PickupProvinceId { get; set; }
        public short? PickupCountryId { get; set; }
        public string PickupPostalCode { get; set; }
        public string PickupGeoCode { get; set; }
        public string PickupInstruction { get; set; }
        public DateTime? EstimateDeliveryDate { get; set; }
        public DateTime? ActualDeliveryDate { get; set; }
        public string DeliveryCompany { get; set; }
        public string DeliveryContactPerson { get; set; }
        public string DeliveryContactNo { get; set; }
        public string DeliveryMobileNo { get; set; }
        public string DeliveryAddress { get; set; }
        public Guid? DeliveryWardId { get; set; }
        public Guid? DeliveryDistrictId { get; set; }
        public Guid? DeliveryProvinceId { get; set; }
        public short? DeliveryCountryId { get; set; }
        public string DeliveryPostalCode { get; set; }
        public string DeliveryGeoCode { get; set; }
        public int? TotalCustomerQuantity { get; set; }
        public decimal? TotalEstimateWeight { get; set; }
        public decimal? TotalEstimateVolume { get; set; }
        public decimal? TotalEstimateChargedWeight { get; set; }
        public int? TotalQuantity { get; set; }
        public decimal? TotalActualWeight { get; set; }
        public decimal? TotalActualVolume { get; set; }
        public decimal? TotalActualChargedWeight { get; set; }
        public int? CommodityId { get; set; }
        public decimal? ItemValue { get; set; }
        public decimal? Codvalue { get; set; }
        public decimal? IndicatedCodvalue { get; set; }
        public string SpecialDeliveryInstruction { get; set; }
        public string InstructionOnUndelivery { get; set; }
        public short? UnitId { get; set; }
        public bool? OverwriteWeight { get; set; }
        public DateTime? OverwriteWeightOn { get; set; }
        public string RevenueProtectionNote { get; set; }
        public int? RateCardId { get; set; }
        public Guid? RateCardConditionId { get; set; }
        public decimal? UnitPrice { get; set; }
        public decimal? TotalExcludeSurcharge { get; set; }
        public decimal? TotalSurcharge { get; set; }
        public decimal? TotalExcludeVat { get; set; }
        public bool? TaxExemption { get; set; }
        public int? Vatrate { get; set; }
        public decimal? Vat { get; set; }
        public decimal? TotaIncludeVat { get; set; }
        public decimal? AdjustedPrice { get; set; }
        public string CurrencyId { get; set; }
        public decimal? TotalCost { get; set; }
        public string Remark { get; set; }
        public bool? IsArising { get; set; }
        public bool? TreatAsAbandoned { get; set; }
        public bool? ReturnToSender { get; set; }
        public bool? Soaclosed { get; set; }
        public string Soano { get; set; }
        public bool? BillingGenerated { get; set; }
        public string BillingNo { get; set; }
        public bool? IsReturnShipment { get; set; }
        public bool? Routed { get; set; }
        public string RoutedBy { get; set; }
        public bool? TransitPickedUp { get; set; }
        public int? BaggedQuantity { get; set; }
        public DateTime? CheckedInOriginBranchOn { get; set; }
        public DateTime? CheckedInDestinationBranchOn { get; set; }
        public decimal? AssignedTransportWeight { get; set; }
        public string SoaadjustmentRequestor { get; set; }
        public DateTime? SoaadjustmentRequestedDate { get; set; }
        public string SoaadjustmentType { get; set; }
        public string SoaadjustmentReason { get; set; }
        public string AdjustedSoauser { get; set; }
        public DateTime? AdjustedSoadate { get; set; }
        public string UnlockedSoasaleMan { get; set; }
        public string UnlockedSoasaleManStatus { get; set; }
        public DateTime? UnlockedSoasaleManDate { get; set; }
        public string UnlockedSoadirector { get; set; }
        public string UnlockedSoadirectorStatus { get; set; }
        public DateTime? UnlockedSoadirectorDate { get; set; }
        public bool? SentEtaemail { get; set; }
        public DateTime? SentEtaemailDate { get; set; }
        public DateTime? EtafromDate { get; set; }
        public decimal? VolumnWeightRate { get; set; }
        public string CustomerBookingNo { get; set; }
        public string WarehouseBookingNo { get; set; }
        public string BookingOverDate { get; set; }
        public bool? IsNotInFixedProject { get; set; }
        public byte[] Version { get; set; }
        public string UserCreated { get; set; }
        public DateTime? DatetimeCreated { get; set; }
        public string UserModified { get; set; }
        public DateTime? DatetimeModified { get; set; }
        public bool? Inactive { get; set; }
        public DateTime? InactiveOn { get; set; }
        public string DelayedTransportByPriceDate { get; set; }
        public string DelayedTransportByOverDueDate { get; set; }
        public string DelayedTransportByCreditDate { get; set; }
        public string Sotype { get; set; }
        public string DeliveryStatus { get; set; }
        public string FailedDeliveryReason { get; set; }
        public string FailedDeliveryDueTo { get; set; }
        public DateTime? PodreceivedDate { get; set; }
        public DateTime? PodhanoverRequestDate { get; set; }
        public DateTime? PodreturnedDate { get; set; }
        public int? PodleadTime { get; set; }
        public string CustomerRouteCode { get; set; }

        public CsOrderHeader Order { get; set; }
    }
}
