export class Partner {
    id: string;
    partnerGroup: string;
    partnerNameVn: string;
    partnerNameEn: string;
    addressVn: string;
    addressEn: string
    shortName: string;
    countryId: number;
    accountNo: string;
    tel: string;
    fax: string;
    taxCode: string;
    email: string;
    website: string;
    bankAccountNo: string;
    bankAccountName: string;
    bankAccountAddress: string;
    note: string;
    salePersonId: string;
    public: boolean;
    creditAmount: 0;
    debitAmount: 0;
    refuseEmail: true;
    receiveAttachedWaybill: true;
    roundedSoamethod: string;
    taxExemption: true;
    receiveEtaemail: true;
    showInDashboard: true;
    provinceId: Date;
    parentId: string;
    percentCredit: number;
    alertPercentCreditEmail: boolean;
    paymentBeneficiary: string;
    usingParrentRateCard: boolean;
    sugarId: string;
    bookingOverdueDay: number;
    fixRevenueByProject: boolean;
    userCreated: string;
    datetimeCreated: Date;
    userModified: string;
    datetimeModified: Date;
    inactive?: boolean;
    inactiveOn?: Date
}