export enum ButtonType {
    add = "add",
    edit = "edit",
    delete = "delete",
    import = "import",
    export = "export",
    save = "save",
    cancel = "cancel",
    reset = "reset",
    detail = "detail",
    closeModal = "closeModal",
    search = "search",
    searchMultiple = 'searchMultiple',
    preview = "preview",
    lock = "lock",
}