using System;

namespace eFMS.API.Setting.DL.Models.Ecus
{
    public class DTOKHAIMD
    {
        public decimal C_DToKhaiMDID { get; set; }
        public string C_XorN { get; set; }
        public Nullable<decimal> SOTK { get; set; }
        public string SOTK_DAU_TIEN { get; set; }
        public Nullable<decimal> SOTK_NHANH { get; set; }
        public Nullable<decimal> SOTK_TONG { get; set; }
        public Nullable<decimal> SOTK_TN_TX { get; set; }
        public string MA_LH { get; set; }
        public string MA_HQ { get; set; }
        public string TEN_HQ { get; set; }
        public Nullable<short> NAMDK { get; set; }
        public Nullable<DateTime> NGAY_DK { get; set; }
        public string MA_DV { get; set; }
        public string MA_BC_DV { get; set; }
        public string DIA_CHI_DV { get; set; }
        public string SO_DT_DV { get; set; }
        public string MA_DVUT { get; set; }
        public string DV_DT { get; set; }
        public string MA_BC_DT { get; set; }
        public string MA_PTVT { get; set; }
        public string TEN_PTVT { get; set; }
        public Nullable<DateTime> NGAYKH { get; set; }
        public Nullable<DateTime> NGAYDEN { get; set; }
        public string VAN_DON { get; set; }
        public string MA_CK { get; set; }
        public string TEN_CK { get; set; }
        public string MA_CANGNN { get; set; }
        public string CANGNN { get; set; }
        public string MA_GP { get; set; }
        public string SO_GP { get; set; }
        public Nullable<DateTime> NGAY_GP { get; set; }
        public Nullable<DateTime> NGAY_HHGP { get; set; }
        public string SO_HD { get; set; }
        public Nullable<double> TYGIA_USD { get; set; }
        public Nullable<DateTime> NGAY_HD { get; set; }
        public Nullable<DateTime> NGAY_HHHD { get; set; }
        public string NUOC_XK { get; set; }
        public string NUOC_NK { get; set; }
        public string MA_GH { get; set; }
        public Nullable<short> SOHANG { get; set; }
        public string MA_PTTT { get; set; }
        public string MA_NT { get; set; }
        public Nullable<double> TYGIA_VND { get; set; }
        public string MA_NT_TY_GIA_VND { get; set; }
        public Nullable<double> LEPHI_HQ { get; set; }
        public string BL_LPHQ { get; set; }
        public string GIAYTO { get; set; }
        public string TENCH { get; set; }
        public Nullable<DateTime> NGAY_KB { get; set; }
        public string USER_DK { get; set; }
        public string DDIEM_KH { get; set; }
        public string PTHUC_KH { get; set; }
        public Nullable<DateTime> NGAY_KH { get; set; }
        public string USER_KH1 { get; set; }
        public string USER_KH2 { get; set; }
        public string USER_PCKH { get; set; }
        public string MA_PHI_BH { get; set; }
        public string MA_NT_PHI_BH { get; set; }
        public Nullable<double> PHI_BH { get; set; }
        public string SO_DK_PHI_BH { get; set; }
        public string MA_PHI_VC { get; set; }
        public string MA_NT_PHI_VC { get; set; }
        public Nullable<double> PHI_VC { get; set; }
        public Nullable<DateTime> NGAY_TH { get; set; }
        public string USER_TH { get; set; }
        public Nullable<double> TONGTGKB { get; set; }
        public Nullable<double> TONGTGTT { get; set; }
        public string MA_NT_TGTT { get; set; }
        public string QUY_VND { get; set; }
        public Nullable<decimal> TR_LUONG { get; set; }
        public string DVT_TR_LUONG { get; set; }
        public Nullable<decimal> SO_KIEN { get; set; }
        public string DVT_KIEN { get; set; }
        public string KY_HIEU_SO_HIEU { get; set; }
        public Nullable<decimal> SO_CONTAINER { get; set; }
        public Nullable<decimal> SO_CONTAINER40 { get; set; }
        public Nullable<decimal> SO_CONTAINER45 { get; set; }
        public string NGUOINHAP { get; set; }
        public Nullable<DateTime> NGAYNHAP { get; set; }
        public string PLUONG { get; set; }
        public Nullable<byte> PASS_DK { get; set; }
        public Nullable<byte> PASS_KH { get; set; }
        public Nullable<byte> PASS_TH { get; set; }
        public Nullable<byte> PASS_GC { get; set; }
        public string TTTK { get; set; }
        public string PPT_GTGT { get; set; }
        public string PPT_GTGTUT { get; set; }
        public string DATRUYEN { get; set; }
        public string MA_DVKT { get; set; }
        public Nullable<byte> THANHKHOAN { get; set; }
        public Nullable<DateTime> NGAY_THN_THX { get; set; }
        public string PPT_GTGTKT { get; set; }
        public Nullable<DateTime> NGAY_GIAOTK { get; set; }
        public Nullable<DateTime> NGAY_NHANTK { get; set; }
        public Nullable<DateTime> NGAY_LUUTK { get; set; }
        public string NVPSINH { get; set; }
        public Nullable<byte> KIEMHOANK { get; set; }
        public string MA_HDTM { get; set; }
        public Nullable<decimal> SO_TN_HDTM { get; set; }
        public string SO_HDTM { get; set; }
        public Nullable<DateTime> NGAY_HDTM { get; set; }
        public string MA_PL_GIA_HDTM { get; set; }
        public Nullable<double> TONGTG_HDTM { get; set; }
        public Nullable<DateTime> NGAY_VANDON { get; set; }
        public Nullable<byte> THUE { get; set; }
        public Nullable<short> HTKT { get; set; }
        public Nullable<decimal> TYLE_KT { get; set; }
        public Nullable<DateTime> DENNGAY_KH { get; set; }
        public string DAIDIEN_DN { get; set; }
        public string NGUOIQDHTKT { get; set; }
        public Nullable<short> SO_PLTK { get; set; }
        public string XUAT_NPL_SP { get; set; }
        public string THANH_LY { get; set; }
        public Nullable<decimal> C_SoTN { get; set; }
        public Nullable<DateTime> C_NgayTN { get; set; }
        public Nullable<short> C_NamTN { get; set; }
        public string C_MaHQTN { get; set; }
        public Nullable<short> C_TrangThai { get; set; }
        public string C_Ten_DV_L1 { get; set; }
        public string C_Ten_DV_L2 { get; set; }
        public string C_Ten_DV_L3 { get; set; }
        public string C_DV_DT_L2 { get; set; }
        public string C_DV_DT_L3 { get; set; }
        public string C_TEN_DVUT { get; set; }
        public string C_TEN_DVKT { get; set; }
        public Nullable<decimal> C_TR_LUONG_Net { get; set; }
        public Nullable<decimal> C_DToKhaiMDIDTempt { get; set; }
        public string C_CT_HDTM_BC { get; set; }
        public string C_CT_HDTM_BS { get; set; }
        public string C_CT_HDonTM_BC { get; set; }
        public string C_CT_HDonTM_BS { get; set; }
        public string C_CT_BK_BC { get; set; }
        public string C_CT_BK_BS { get; set; }
        public string C_CT_VD_BC { get; set; }
        public string C_CT_VD_BS { get; set; }
        public string C_CT_Them1_Ten { get; set; }
        public string C_CT_Them1_BC { get; set; }
        public string C_CT_Them1_BS { get; set; }
        public string C_CT_Them2_Ten { get; set; }
        public string C_CT_Them2_BC { get; set; }
        public string C_CT_Them2_BS { get; set; }
        public string C_CT_Them3_Ten { get; set; }
        public string C_CT_Them3_BC { get; set; }
        public string C_CT_Them3_BS { get; set; }
        public Nullable<decimal> C_MA_PHU_Max { get; set; }
        public string C_THANH_LY_BackUp { get; set; }
        public Nullable<int> IsNhanHS { get; set; }
        public Nullable<decimal> HeSoNhanTGTT { get; set; }
        public Nullable<int> isPhanBo { get; set; }
        public string MA_NT_THUE { get; set; }
        public Nullable<decimal> TongTienThue { get; set; }
        public Nullable<decimal> TongTienThueKH { get; set; }
        public Nullable<decimal> TongTienThueTH { get; set; }
        public Nullable<double> HeSoCIFDN { get; set; }
        public Nullable<int> isUseHeSoCIFDN { get; set; }
        public string TTTK_HQ { get; set; }
        public string SoHDXK { get; set; }
        public Nullable<DateTime> NgayDKNhapHang { get; set; }
        public string KDT_WAITING { get; set; }
        public string KDT_REFERENCES { get; set; }
        public string KDT_LASTINFO { get; set; }
        public Nullable<int> IsNewInfomation { get; set; }
        public Nullable<decimal> DToKhaiMDID_ERP { get; set; }
        public Nullable<decimal> DVan_DonID { get; set; }
        public string MA_HQ_CK { get; set; }
        public string MessageID { get; set; }
        public string LyDoHuy { get; set; }
        public string TinhTrang_NoCO { get; set; }
        public string TinhTrang_HUY { get; set; }
        public Nullable<decimal> PreToKhaiID { get; set; }
        public string PhienBan_TK { get; set; }
        public Nullable<decimal> NextToKhaiID { get; set; }
        public string HuongDanPL { get; set; }
        public string Chuyen_Cua_Khau { get; set; }
        public string Noi_Dung_Chuyen_Cua_Khau { get; set; }
        public string LyDoSua { get; set; }
        public string TTTK_HUY { get; set; }
        public string Ma_MID { get; set; }
        public Nullable<DateTime> NGAY_HOANTHANH { get; set; }
        public Nullable<int> ThueTuyetDoi { get; set; }
        public Nullable<int> IsDaDuyet { get; set; }
        public string NguoiDuyet { get; set; }
        public Nullable<DateTime> NgayDuyet { get; set; }
        public string GhiChuDuyet { get; set; }
        public Nullable<int> IsExport { get; set; }
        public Nullable<int> IsSign { get; set; }
        public string SignData { get; set; }
        public string SoHSTK { get; set; }
        public Nullable<decimal> HDGCID { get; set; }
        public string SO_HD_CT { get; set; }
        public Nullable<DateTime> NGAY_HD_CT { get; set; }
        public Nullable<DateTime> NGAY_HHHD_CT { get; set; }
        public string DIA_DIEM_GIAO_HANG { get; set; }
        public Nullable<DateTime> NGAY_GIAO_HANG { get; set; }
        public string MA_NGUOI_CHI_DINH_CT { get; set; }
        public string TEN_NGUOI_CHI_DINH_CT { get; set; }
        public Nullable<int> IsToKhaiCT { get; set; }
        public string DeXuatKhac { get; set; }
        public Nullable<int> IsToKhaiNho { get; set; }
        public string HUY_MA_LY_DO { get; set; }
        public string HUY_MA_LOAI { get; set; }
        public string HUY_TrangThai { get; set; }
        public Nullable<decimal> HUY_SOTN { get; set; }
        public Nullable<decimal> HUY_NAMTN { get; set; }
        public Nullable<DateTime> HUY_NgayTN { get; set; }
        public string HUY_MessageID { get; set; }
        public Nullable<int> HUY_IsSign { get; set; }
        public string HUY_SignData { get; set; }
        public string TUYEN_VAN_CHUYEN { get; set; }
        public string Ten_Nguoi_Nhan_Hang { get; set; }
        public string Ma_Nguoi_Nhan_Hang { get; set; }
        public string Ten_Nguoi_Giao_Hang { get; set; }
        public string Ma_Nguoi_Giao_Hang { get; set; }
        public Nullable<int> IsTQDT { get; set; }
        public Nullable<int> KieuPhanBo { get; set; }
        public Nullable<int> Chon { get; set; }
        public string ThongTinPhanHoi { get; set; }
        public Nullable<double> PHI_KHAC { get; set; }
        public string TEN_PHI_KHAC { get; set; }
        public string HuyKB { get; set; }
        public Nullable<DateTime> NGAY_BAT_DAU { get; set; }
        public Nullable<DateTime> NGAY_KET_THUC { get; set; }
        public string HUY_KDT_REFERENCES { get; set; }
        public string HUY_KDT_WAITING { get; set; }
        public string HUY_KDT_LASTINFO { get; set; }
        public Nullable<int> isUseHeSoI { get; set; }
        public Nullable<DateTime> NGAY_THUC_XN { get; set; }
        public string PLUONG_NOIDUNG { get; set; }
        public Nullable<int> IS_TRINH_KY { get; set; }
        public Nullable<int> HUY_IS_TRINH_KY { get; set; }
        public Nullable<int> IsKHONG_VAN_DON { get; set; }
        public Nullable<int> IS_AN_HAN_THUE { get; set; }
        public string AN_HAN_THUE_LD { get; set; }
        public Nullable<decimal> AN_HAN_THUE_SN { get; set; }
        public Nullable<int> IS_DAM_BAO_THUE { get; set; }
        public string DAM_BAO_THUE_HINH_THUC { get; set; }
        public Nullable<double> DAM_BAO_THUE_TRI_GIA { get; set; }
        public Nullable<DateTime> DAM_BAO_THUE_NGAY_BD { get; set; }
        public Nullable<DateTime> DAM_BAO_THUE_NGAY_KT { get; set; }
        public string DAM_BAO_MA_NG_HANG { get; set; }
        public Nullable<int> DAM_BAO_NAM_PHAT_HANH { get; set; }
        public string DAM_BAO_KY_HIEU_CT { get; set; }
        public string DAM_BAO_SO_CT { get; set; }
        public string MA_THOI_HAN_NOP_THUE { get; set; }
        public Nullable<decimal> SO_CONTAINER_KHAC { get; set; }
        public Nullable<DateTime> NGAY_TAM_NHAP_HH { get; set; }
        public Nullable<decimal> THONG_TU { get; set; }
        public string MA_NGHIEP_VU { get; set; }
        public string GUID1 { get; set; }
        public string NHOMTK { get; set; }
        public Nullable<int> ISTEST { get; set; }
        public Nullable<int> IsVNACCS { get; set; }
        public string APP_NAME { get; set; }
        public Nullable<int> IsVersion2 { get; set; }
        public string TRANG_THAI_SAMSUNG { get; set; }
        public string THANH_LY_KBT { get; set; }
        public string SECSIONID { get; set; }
        public Nullable<int> IsUyQuyen { get; set; }
        public Nullable<decimal> DSCH810AWBID { get; set; }
        public Nullable<int> IS_DUYET { get; set; }
        public string USER_DUYET { get; set; }
    }
}
