//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eFMSWindowService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class catDepartment
    {
        public int ID { get; set; }
        public string Code { get; set; }
        public string DeptName { get; set; }
        public string DeptNameEn { get; set; }
        public string DeptNameAbbr { get; set; }
        public string Description { get; set; }
        public Nullable<System.Guid> BranchID { get; set; }
        public string DeptType { get; set; }
        public string Email { get; set; }
        public string UserCreated { get; set; }
        public Nullable<System.DateTime> DatetimeCreated { get; set; }
        public string UserModified { get; set; }
        public Nullable<System.DateTime> DatetimeModified { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> InactiveOn { get; set; }
    }
}
