//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eFMSWindowService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class csTransaction
    {
        public System.Guid ID { get; set; }
        public System.Guid BranchID { get; set; }
        public string JobNo { get; set; }
        public string MAWB { get; set; }
        public string TypeOfService { get; set; }
        public Nullable<System.DateTime> ETD { get; set; }
        public Nullable<System.DateTime> ETA { get; set; }
        public Nullable<System.DateTime> ServiceDate { get; set; }
        public string MBLType { get; set; }
        public string ColoaderID { get; set; }
        public string SubColoader { get; set; }
        public string BookingNo { get; set; }
        public string AgentID { get; set; }
        public Nullable<System.Guid> POL { get; set; }
        public Nullable<System.Guid> POD { get; set; }
        public Nullable<System.Guid> WarehouseID { get; set; }
        public Nullable<System.Guid> DeliveryPlace { get; set; }
        public string PaymentTerm { get; set; }
        public string FlightVesselName { get; set; }
        public string VoyNo { get; set; }
        public string ShipmentType { get; set; }
        public string Commodity { get; set; }
        public string DesOfGoods { get; set; }
        public string PackageContainer { get; set; }
        public string PONo { get; set; }
        public string PersonIncharge { get; set; }
        public Nullable<decimal> NetWeight { get; set; }
        public Nullable<decimal> GrossWeight { get; set; }
        public Nullable<decimal> ChargeWeight { get; set; }
        public Nullable<decimal> CBM { get; set; }
        public Nullable<decimal> HW { get; set; }
        public Nullable<int> PackageQty { get; set; }
        public string PackageType { get; set; }
        public string Notes { get; set; }
        public string TransactionType { get; set; }
        public string CurrentStatus { get; set; }
        public Nullable<System.DateTime> LockedDate { get; set; }
        public string LockedLog { get; set; }
        public Nullable<bool> IsLocked { get; set; }
        public Nullable<System.DateTime> FlightDate { get; set; }
        public Nullable<decimal> HWConstant { get; set; }
        public string Route { get; set; }
        public string UserCreated { get; set; }
        public Nullable<System.DateTime> DatetimeCreated { get; set; }
        public string UserModified { get; set; }
        public Nullable<System.DateTime> DatetimeModified { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> InactiveOn { get; set; }
        public string IssuedBy { get; set; }
        public Nullable<short> GroupID { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<System.Guid> OfficeID { get; set; }
        public Nullable<System.Guid> CompanyID { get; set; }
    }
}
