//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eFMSWindowService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_catCurrencyExchangeNewest
    {
        public int ID { get; set; }
        public string CurrencyFromID { get; set; }
        public decimal Rate { get; set; }
        public Nullable<System.DateTime> DatetimeCreated { get; set; }
        public string CurrencyToID { get; set; }
    }
}
